# Generated by Django 3.1.6 on 2021-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('FREELANCE', 'FREELANCE'), ('INVESTER', 'INVESTER')], default='FREELANCE', max_length=40),
        ),
    ]
