# Generated by Django 3.1.6 on 2021-02-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20210217_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qa',
            old_name='owner',
            new_name='user',
        ),
    ]
