# Generated by Django 3.1.6 on 2021-02-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_auto_20210217_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='qa',
        ),
    ]
