# Generated by Django 3.1.6 on 2021-02-17 12:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('discussion', '0004_remove_answer_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
